Handle PR from fork

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -205,15 +205,10 @@ jobs:
     docker:
       - image: cimg/php:7.4-node
     steps:
-      - run: |
-          if [ -z "$CIRCLE_PR_NUMBER" ]; then
-            echo "This is an internal PR. Proceed with additional testing."
-          fi
-          else
-            echo "This PR is from a fork. A staff member must test it manually."
-            exit 1;
-          fi
       - attach_workspace: {at: /tmp}
+      - run:
+          #Fail when the PR comes from a fork.
+          command: '[ -n "$CIRCLE_PR_NUMBER" ] && echo "A staff member will internally test your PR. Thanks!" && exit 1'
       - run:
           #Fail when there is no PR. This helps avoid false positives given by Danger when no PR exists.
           command: '[ -n "$CIRCLE_PULL_REQUEST" ] && DANGER_GITHUB_API_TOKEN=$GITHUB_MASSGOV_BOT_TOKEN yarn danger ci --failOnErrors'
